name: digital_study_room
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.0.4+5
#version: 1.0.5+6 #Tutor section redesigned
version: 1.0.6+7 #Tutor Id added, tutors come according to class

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.1.0
  avatar_glow: ^3.0.1
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  connectivity_plus: ^5.0.2
#  video_player: ^2.8.2
#  chewie: ^1.2.2
#  youtube_player_flutter: ^9.1.1
  flutter_spinkit: ^5.2.0

  audioplayers: ^5.2.1
  just_audio: ^0.9.42
  record: ^5.2.1

  shurjopay: ^2.0.3
  flutter_math_fork: ^0.7.2
  speech_to_text: ^6.6.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.3
#  hovering: ^1.0.4
  shared_preferences: ^2.2.2
  permission_handler: ^11.4.0

  flutter_screenutil: ^5.9.3
  lottie: ^3.2.0

  # File Handling & Storage
  file_picker: ^9.0.2
  path_provider: ^2.1.2
  open_file: ^3.3.2
  pdfx: ^2.8.0
  syncfusion_flutter_pdfviewer: ^26.2.10 # Add this for PDF viewing

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^9.0.0

  # State Management
  get_storage: ^2.1.1
  provider: ^6.1.2


  # Product Specific
  markdown_widget: ^2.3.2+6
  flutter_inappwebview: ^6.1.0+1

  screenshot: ^3.0.0
  share_plus: ^7.0.1

  image: ^4.0.17



dev_dependencies:
  flutter_test:
    sdk: flutter


  adaptive_navigation: ^0.0.9

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  background_color_ios: "#ffffff"
  image_path: "assets/icons/dsr_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  windows:
    generate: true
    image_path: "assets/icons/dsr_icon.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:
  uses-material-design: true

  # ---------- LOCAL ASSETS ----------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/animations/
    - assets/images/dashboard_images/
    - assets/images/items/

  # ---------- LOCAL FONTS ----------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
